### ISSUE TITLE
Use type from @graphql-typed-document-node/core

### ISSUE THREAD

**Issue by hallettj** [Thinkmill/ts-gql#50]
This project is so helpful - thank you for making it!

I wanted to suggest switching the type exported from generated code to the `TypedDocumentNode` type from the `@graphql-typed-document-node/core` package. The reason is that Apollo Client, and possibly other libraries, accept this type, and correctly propagate types for result data, and for variables. IMO that makes `@graphql-typed-document-node/core` a sort of standard for typed queries. If you use it then queries typed by `@ts-gql` could be used in other contexts without custom wrappers to match up types.

The definition from `@graphql-typed-document-node/core` looks like this:

```ts
import { DocumentNode } from 'graphql';
export interface TypedDocumentNode<Result = {
    [key: string]: any;
}, Variables = {
    [key: string]: any;
}> extends DocumentNode {
    __resultType?: Result;
    __variablesType?: Variables;
}
/**
 * Helper for extracting a TypeScript type for operation result from a TypedDocumentNode.
 * @example
 * const myQuery = { ... }; // TypedDocumentNode<R, V>
 * type ResultType = ResultOf<typeof myQuery>; // Now it's R
 */
export declare type ResultOf<T> = T extends TypedDocumentNode<infer ResultType, infer VariablesType> ? ResultType : never;
/**
 * Helper for extracting a TypeScript type for operation variables from a TypedDocumentNode.
 * @example
 * const myQuery = { ... }; // TypedDocumentNode<R, V>
 * type VariablesType = ResultOf<typeof myQuery>; // Now it's V
 */
export declare type VariablesOf<T> = T extends TypedDocumentNode<infer ResultType, infer VariablesType> ? VariablesType : never;
```

**Comment by mitchellhamilton** [comment]
Happy to accept a PR that makes ts-gql's TypedDocumentNode intersect with the one from `@graphql-typed-document-node/core` though there are some things that `@graphql-typed-document-node/core` wouldn't support(typing of refetchQueries with the specific queries that are available) so I'd rather not switch completely.
