### ISSUE TITLE
ts-gql watch crashes when a query is removed

### ISSUE THREAD

**Issue by Noviny** [Thinkmill/ts-gql#52]
Repro:
1. create a query and set it up correctly
2. Start a watching server
3. Delete the query that you have created
4. ts-gql watch crashes

**Comment by mitchellhamilton** [comment]
Have you got a stack trace from when it crashes? I can't reproduce this

**Comment by Noviny** [comment]
`Error: ENOENT: no such file or directory, unlink '/Users/noviny/Development/40k-app/__generated__/ts-gql/createABattle.ts'`

Just a note, I narrowed this down to something different. The things that trigger this are:

1. removing the `import` statement while watching
2. changing the name of the query (or mutation) while watch is running
